config/routes.rb
Rails.application.routes.draw do
  resources :locations
  
  root 'locations#new'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    
    geocoded_by :full_street_address
    after_validation :geocode
    
    def full_street_address
       "#{street_address}, #{city}, GA" 
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  include LocationsHelper
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    bus_api_url = "http://developer.itsmarta.com/BRDRestService/RestBusRealTimeService/GetAllBus"
    
    @buses = fetch_buses_from_api(bus_api_url)
    
    @buses.select! do |bus|
      
      is_nearby?(@location.latitude, @location.longitude, bus["LATITUDE"], bus["LONGITUDE"])
      
    end
    
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:street_address, :city, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
    
    def fetch_buses_from_api(bus_api_url)
       
        raw_http = Net::HTTP.get_response(URI.parse(bus_api_url))
        bus_data = raw_http.body
        
        JSON.parse(bus_data)
        
    end
    
    def is_nearby?(user_lat, user_long, bus_lat, bus_long)
        
       max_distance = 0.01 # in degrees, approximately .5 mile
       
       difference_latitudes = user_lat - bus_lat.to_f
       difference_longitudes = user_long - bus_long.to_f
       
       distance = Math.sqrt(difference_latitudes ** 2 + difference_longitudes **2)
       
       distance <= max_distance
        
    end
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AtlantaBusLocator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label 'Address or Approximate Location' %>
    <%= form.text_field :street_address, id: :location_street_address , class: 'form control' %>
  </div>

  <div class="field form-group">
    
    <%= form.label :city %>
    <%= form.text_field :city, id: :location_city, class: 'form control' %>
  </div>


  <div class="actions form-group">
    <%= form.submit "Find my bus!", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Street address</th>
      <th>City</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.street_address %></td>
        <td><%= location.city %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3
                    col-sm-8 col-sm-offset-2
                    col-xs-10 col-sm-offset-1">
            
            <h1 class="text-center">FIND ME A BUS IN ATLANTA</h1>

            <p>Give us your address or corner and we'll let you know if a bus is close by.</p>

            <%= render 'form', location: @location %>
            
        </div>
    </div>
</div>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Nearby Buses</h1>

<h3 class="text-muted">Your current location</h3>

  <p class="text-muted">
    <%= @location.full_street_address %> <small><%= link_to fa_icon('pencil', text: 'Edit'), edit_location_path(@location) %></small>
  
  </p>

  <div id="map-canvas"></div>


<!-- List all the buses -->
<h3>The closest buses are...</h3>
  <% @buses.each do |bus| %>
    <div class="well">
      <strong>Route: </strong><%= bus['ROUTE'] %> <%= bus['DIRECTION'] %>
    <br>
      <strong>Bus Number: </strong> <%= bus['VEHICLE'] %>
    <br>
      <strong>Next Stop: </strong> <%= bus['TIMEPOINT'] %>
    </div>
  <% end %>
  
  <% if @buses.empty? %>
    <p>
      Not really that close. Time to walk, bike, taxi, Uber, frolic or <%= link_to 'edit your location', edit_location_path(@location) %>
    </p>
  <% end %>
  
  <%= link_to 'Edit', edit_location_path(@location) %>
  
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_maps_api_key'] %>"></script>

<script>
  function initialize() {
    var myLocation = new google.maps.LatLng(<%= @location.latitude %>, <%= @location.longitude %>)
    var mapOptions = {
      center: myLocation,
      zoom: 15
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    var personIcon = "<%= image_path 'man_icon.png' %>";
    var myMarker = new google.maps.Marker({
      position: myLocation,
      map: map,
      animation: google.maps.Animation.DROP,
      title: 'My Location',
      icon: personIcon
    });



      var myContentString = `<div id="content">
        <h2>Your location</h2>
        <div id="bodyContent">
          <p><%= @location.full_street_address %></p>
        </div>
      </div>`

      var myInfoWindow = new google.maps.InfoWindow({
        content: myContentString
      });
      
      google.maps.event.addListener(myMarker, 'click', function() {
        myInfoWindow.open(map, myMarker);
      });
      
    
    var nearbyBuses = <%= raw @buses.to_json %>;
    nearbyBuses.forEach(function(bus) {
      var busLocation = new google.maps.LatLng(bus['LATITUDE'], bus['LONGITUDE']);
      var busMarker = new google.maps.Marker({
        position: busLocation,
        map: map,
        animation: google.maps.Animation.DROP,
        title: bus['VEHICLE']
      });
      var contentString = `<div id="content">
        <h2>Bus ${bus['VEHICLE']} ${bus['DIRECTION']}</h2>
        <div id="bodyContent">
          <p>Next Stop: ${bus['TIMEPOINT']}</p>
        </div>
      </div>`
      var infoWindow = new google.maps.InfoWindow({
        content: contentString
      });
      google.maps.event.addListener(busMarker, 'click', function() {
        infoWindow.open(map, busMarker);
      });
      

      
    });
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>